.\" Generated with the mancreator
.\" kai gonzalez 2021
.
.TH "HELLO" "1" "August 2021" "1.0" "Kai's Command Essentials Manual"
.
.SH "NAME"
\fBhello\fR \- The binary that\'s produced by sources\.mk
.
.SH "SYNOPSIS"
\fBhello\fR
.
.SH "DESCRIPTION"
hello is the binary file produced when running \fBmake\fR from the / directory of the helloluac project\.
.
.P
the hello file is bound by the hellolua\.c file found in the \fB/\fR (root) directory\.
